In [32]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [33]:
transpot = pd.read_csv('../../processed_data/PPMI/Transcriptomics/transpot_all.csv',).drop("Unnamed: 0", axis=1)
img = pd.read_pickle('../../data/PPMI/MRI_nobrain/mri_meta_2D_4class_nobrain.pkl')[["img_array", "PATNO Visit", "label"]]

In [34]:
img

                                             img_array PATNO Visit label
0    [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   14426_V06     2
1    [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...    14426_BL     2
2    [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...    15761_BL     2
3    [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   16644_V04     2
4    [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   16644_V06     2
..                                                 ...         ...   ...
814  [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   85236_V04     2
815  [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   85236_V06     2
816  [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...    85242_BL     2
817  [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   85242_V04     2
818  [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   85242_V06     2

[819 rows x 3 columns]

In [35]:
img = img.reset_index(drop=True)

In [36]:
img

                                             img_array PATNO Visit label
0    [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   14426_V06     2
1    [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...    14426_BL     2
2    [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...    15761_BL     2
3    [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   16644_V04     2
4    [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   16644_V06     2
..                                                 ...         ...   ...
814  [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   85236_V04     2
815  [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   85236_V06     2
816  [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...    85242_BL     2
817  [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   85242_V04     2
818  [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...   85242_V06     2

[819 rows x 3 columns]

In [37]:
img['img_array'][0].shape

(3, 72, 72)

In [38]:
overlap=pd.merge(transpot,img,on='PATNO Visit',how='inner')

In [39]:
overlap

,PATNO Visit,label_x,ENSG00000242268.2,ENSG00000259041.1,ENSG00000207641.1,ENSG00000270112.3,ENSG00000280143.1,ENSG00000269416.5,ENSG00000263642.1,ENSG00000225275.4,...,ENSG00000216352.1,ENSG00000123685.8,ENSG00000267117.1,ENSG00000265520.1,ENSG00000105063.18,ENSG00000181518.4,ENSG00000231119.2,ENSG00000178921.13,img_array,label_y
0,60044_V06,2,3,0,0,2,38,1,116,0,...,0,75,0,3,1792,0,2,186,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",2
1,3815_BL,1,0,0,0,1,19,0,33,0,...,0,64,0,2,1183,0,5,236,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
2,3834_V04,1,0,0,0,2,16,0,87,0,...,0,91,0,0,2497,0,0,438,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
3,3756_V04,0,0,0,0,0,6,0,34,0,...,0,34,0,0,1098,0,4,108,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",0
4,60024_V04,2,0,0,0,1,7,0,24,0,...,0,96,0,0,782,0,1,83,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,3584_V04,1,0,0,0,6,12,1,37,0,...,0,93,1,0,1002,0,2,62,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
622,3826_V06,1,1,1,0,2,7,1,45,0,...,4,52,0,0,728,3,0,127,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
623,3814_V06,1,0,0,0,1,16,1,79,0,...,0,75,1,0,1327,0,5,220,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
624,3325_V04,1,1,0,0,1,9,0,36,0,...,0,86,0,3,1498,2,1,217,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
625,4005_V04,1,0,0,1,1,9,3,34,1,...,0,46,1,0,648,2,7,97,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1

In [40]:
overlap=overlap.drop(['label_x'],axis=1)

In [41]:
overlap

,PATNO Visit,ENSG00000242268.2,ENSG00000259041.1,ENSG00000207641.1,ENSG00000270112.3,ENSG00000280143.1,ENSG00000269416.5,ENSG00000263642.1,ENSG00000225275.4,ENSG00000158486.13,...,ENSG00000216352.1,ENSG00000123685.8,ENSG00000267117.1,ENSG00000265520.1,ENSG00000105063.18,ENSG00000181518.4,ENSG00000231119.2,ENSG00000178921.13,img_array,label_y
0,60044_V06,3,0,0,2,38,1,116,0,3,...,0,75,0,3,1792,0,2,186,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",2
1,3815_BL,0,0,0,1,19,0,33,0,5,...,0,64,0,2,1183,0,5,236,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
2,3834_V04,0,0,0,2,16,0,87,0,3,...,0,91,0,0,2497,0,0,438,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
3,3756_V04,0,0,0,0,6,0,34,0,0,...,0,34,0,0,1098,0,4,108,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",0
4,60024_V04,0,0,0,1,7,0,24,0,1,...,0,96,0,0,782,0,1,83,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,3584_V04,0,0,0,6,12,1,37,0,23,...,0,93,1,0,1002,0,2,62,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
622,3826_V06,1,1,0,2,7,1,45,0,15,...,4,52,0,0,728,3,0,127,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
623,3814_V06,0,0,0,1,16,1,79,0,19,...,0,75,1,0,1327,0,5,220,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
624,3325_V04,1,0,0,1,9,0,36,0,7,...,0,86,0,3,1498,2,1,217,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
625,4005_V04,0,0,1,1,9,3,34,1,18,...,0,46,1,0,648,2,7,97,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1

In [42]:
overlap=overlap.rename(columns={'label_y':'label'})

In [43]:
overlap

,PATNO Visit,ENSG00000242268.2,ENSG00000259041.1,ENSG00000207641.1,ENSG00000270112.3,ENSG00000280143.1,ENSG00000269416.5,ENSG00000263642.1,ENSG00000225275.4,ENSG00000158486.13,...,ENSG00000216352.1,ENSG00000123685.8,ENSG00000267117.1,ENSG00000265520.1,ENSG00000105063.18,ENSG00000181518.4,ENSG00000231119.2,ENSG00000178921.13,img_array,label
0,60044_V06,3,0,0,2,38,1,116,0,3,...,0,75,0,3,1792,0,2,186,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",2
1,3815_BL,0,0,0,1,19,0,33,0,5,...,0,64,0,2,1183,0,5,236,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
2,3834_V04,0,0,0,2,16,0,87,0,3,...,0,91,0,0,2497,0,0,438,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
3,3756_V04,0,0,0,0,6,0,34,0,0,...,0,34,0,0,1098,0,4,108,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",0
4,60024_V04,0,0,0,1,7,0,24,0,1,...,0,96,0,0,782,0,1,83,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,3584_V04,0,0,0,6,12,1,37,0,23,...,0,93,1,0,1002,0,2,62,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
622,3826_V06,1,1,0,2,7,1,45,0,15,...,4,52,0,0,728,3,0,127,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
623,3814_V06,0,0,0,1,16,1,79,0,19,...,0,75,1,0,1327,0,5,220,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
624,3325_V04,1,0,0,1,9,0,36,0,7,...,0,86,0,3,1498,2,1,217,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
625,4005_V04,0,0,1,1,9,3,34,1,18,...,0,46,1,0,648,2,7,97,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1

In [44]:
overlap.to_csv('../../processed_data/PPMI/overlap/all.csv')

## 统一测试集

In [45]:
overlap.index=overlap['PATNO Visit']

## 不统一测试集

In [46]:
overlap

,PATNO Visit,ENSG00000242268.2,ENSG00000259041.1,ENSG00000207641.1,ENSG00000270112.3,ENSG00000280143.1,ENSG00000269416.5,ENSG00000263642.1,ENSG00000225275.4,ENSG00000158486.13,...,ENSG00000216352.1,ENSG00000123685.8,ENSG00000267117.1,ENSG00000265520.1,ENSG00000105063.18,ENSG00000181518.4,ENSG00000231119.2,ENSG00000178921.13,img_array,label
PATNO Visit,,,,,,,,,,,,,,,,,,,,,
60044_V06,60044_V06,3,0,0,2,38,1,116,0,3,...,0,75,0,3,1792,0,2,186,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",2
3815_BL,3815_BL,0,0,0,1,19,0,33,0,5,...,0,64,0,2,1183,0,5,236,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
3834_V04,3834_V04,0,0,0,2,16,0,87,0,3,...,0,91,0,0,2497,0,0,438,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
3756_V04,3756_V04,0,0,0,0,6,0,34,0,0,...,0,34,0,0,1098,0,4,108,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",0
60024_V04,60024_V04,0,0,0,1,7,0,24,0,1,...,0,96,0,0,782,0,1,83,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3584_V04,3584_V04,0,0,0,6,12,1,37,0,23,...,0,93,1,0,1002,0,2,62,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
3826_V06,3826_V06,1,1,0,2,7,1,45,0,15,...,4,52,0,0,728,3,0,127,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
3814_V06,3814_V06,0,0,0,1,16,1,79,0,19,...,0,75,1,0,1327,0,5,220,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
3325_V04,3325_V04,1,0,0,1,9,0,36,0,7,...,0,86,0,3,1498,2,1,217,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1
4005_V04,4005_V04,0,0,1,1,9,3,34,1,18,...,0,46,1,0,648,2,7,97,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...",1

In [47]:
X= overlap.drop(['PATNO Visit','label'],axis=1)
y = overlap['label']

In [48]:
X

,ENSG00000242268.2,ENSG00000259041.1,ENSG00000207641.1,ENSG00000270112.3,ENSG00000280143.1,ENSG00000269416.5,ENSG00000263642.1,ENSG00000225275.4,ENSG00000158486.13,ENSG00000283967.1,...,ENSG00000238244.3,ENSG00000216352.1,ENSG00000123685.8,ENSG00000267117.1,ENSG00000265520.1,ENSG00000105063.18,ENSG00000181518.4,ENSG00000231119.2,ENSG00000178921.13,img_array
PATNO Visit,,,,,,,,,,,,,,,,,,,,,
60044_V06,3,0,0,2,38,1,116,0,3,0,...,3,0,75,0,3,1792,0,2,186,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3815_BL,0,0,0,1,19,0,33,0,5,0,...,0,0,64,0,2,1183,0,5,236,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3834_V04,0,0,0,2,16,0,87,0,3,0,...,1,0,91,0,0,2497,0,0,438,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3756_V04,0,0,0,0,6,0,34,0,0,0,...,0,0,34,0,0,1098,0,4,108,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
60024_V04,0,0,0,1,7,0,24,0,1,0,...,1,0,96,0,0,782,0,1,83,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3584_V04,0,0,0,6,12,1,37,0,23,0,...,3,0,93,1,0,1002,0,2,62,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3826_V06,1,1,0,2,7,1,45,0,15,0,...,0,4,52,0,0,728,3,0,127,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3814_V06,0,0,0,1,16,1,79,0,19,0,...,0,0,75,1,0,1327,0,5,220,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3325_V04,1,0,0,1,9,0,36,0,7,0,...,0,0,86,0,3,1498,2,1,217,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
4005_V04,0,0,1,1,9,3,34,1,18,0,...,0,0,46,1,0,648,2,7,97,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."

In [60]:
y.shape

(626,)

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, stratify=y)

In [57]:
X_temp.shape

(251, 57704)

In [58]:
y_temp.shape

(251,)

In [61]:
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, stratify=y_temp)

In [62]:
X_train

,ENSG00000242268.2,ENSG00000259041.1,ENSG00000207641.1,ENSG00000270112.3,ENSG00000280143.1,ENSG00000269416.5,ENSG00000263642.1,ENSG00000225275.4,ENSG00000158486.13,ENSG00000283967.1,...,ENSG00000238244.3,ENSG00000216352.1,ENSG00000123685.8,ENSG00000267117.1,ENSG00000265520.1,ENSG00000105063.18,ENSG00000181518.4,ENSG00000231119.2,ENSG00000178921.13,img_array
PATNO Visit,,,,,,,,,,,,,,,,,,,,,
3390_BL,2,0,0,16,11,3,23,1,19,0,...,0,0,79,2,2,619,5,4,81,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
4020_V06,0,2,0,2,8,3,22,0,19,0,...,2,0,36,0,1,582,7,2,63,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
4020_BL,0,0,0,0,8,0,46,2,1,0,...,3,0,42,0,0,1482,0,0,114,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3770_V04,0,0,1,0,0,1,8,0,5,0,...,1,0,32,0,2,401,0,2,53,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3165_BL,0,0,0,0,13,0,27,0,2,0,...,2,0,41,0,2,958,0,2,170,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3173_BL,0,0,0,0,8,0,27,0,3,0,...,0,0,118,0,9,2458,0,2,269,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3119_BL,0,0,0,2,8,0,64,2,3,0,...,0,0,105,0,0,1420,0,1,185,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3752_V06,0,0,0,0,18,0,29,0,5,0,...,1,0,264,0,9,1506,0,4,268,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3132_V04,2,0,0,5,14,1,30,1,8,0,...,0,0,34,0,1,736,1,3,91,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3182_BL,4,4,0,28,20,5,52,3,97,0,...,3,1,60,2,1,644,7,4,80,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."

In [63]:
X_val

,ENSG00000242268.2,ENSG00000259041.1,ENSG00000207641.1,ENSG00000270112.3,ENSG00000280143.1,ENSG00000269416.5,ENSG00000263642.1,ENSG00000225275.4,ENSG00000158486.13,ENSG00000283967.1,...,ENSG00000238244.3,ENSG00000216352.1,ENSG00000123685.8,ENSG00000267117.1,ENSG00000265520.1,ENSG00000105063.18,ENSG00000181518.4,ENSG00000231119.2,ENSG00000178921.13,img_array
PATNO Visit,,,,,,,,,,,,,,,,,,,,,
3154_BL,0,0,0,2,15,0,38,0,9,0,...,3,0,109,0,2,1063,1,2,198,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3106_V04,0,0,0,0,8,1,49,0,1,0,...,0,0,55,0,0,960,0,0,104,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3165_V04,1,0,0,1,3,0,15,0,1,0,...,0,0,46,0,2,857,1,3,127,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3150_BL,0,0,0,0,7,0,27,0,3,0,...,0,0,102,0,2,1286,0,1,256,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3822_V04,1,3,0,5,22,2,72,0,28,0,...,2,0,62,2,2,1566,5,3,297,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3178_V06,7,10,4,59,44,15,78,6,285,0,...,3,7,77,5,3,1162,25,18,164,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
60091_BL,0,0,0,0,4,1,29,0,2,0,...,0,0,41,0,2,911,0,1,113,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3185_BL,0,0,0,18,29,5,70,1,34,0,...,5,0,54,1,2,1917,6,3,322,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3857_V06,7,12,0,72,73,34,19,4,283,0,...,8,6,55,5,1,450,37,20,169,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3819_V04,0,0,0,1,11,0,50,0,2,0,...,2,0,56,0,6,959,0,2,132,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."

In [64]:
X_test

,ENSG00000242268.2,ENSG00000259041.1,ENSG00000207641.1,ENSG00000270112.3,ENSG00000280143.1,ENSG00000269416.5,ENSG00000263642.1,ENSG00000225275.4,ENSG00000158486.13,ENSG00000283967.1,...,ENSG00000238244.3,ENSG00000216352.1,ENSG00000123685.8,ENSG00000267117.1,ENSG00000265520.1,ENSG00000105063.18,ENSG00000181518.4,ENSG00000231119.2,ENSG00000178921.13,img_array
PATNO Visit,,,,,,,,,,,,,,,,,,,,,
3101_BL,1,0,0,15,17,4,19,1,45,0,...,1,0,62,2,0,770,8,5,163,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
4005_V04,0,0,1,1,9,3,34,1,18,0,...,0,0,46,1,0,648,2,7,97,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3808_V06,0,0,0,0,20,2,140,0,1,0,...,0,0,72,0,9,1806,0,3,299,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3318_V06,1,0,0,7,17,3,58,1,20,0,...,4,1,100,1,4,1575,5,7,217,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3360_V04,0,0,0,1,13,1,28,0,0,0,...,0,0,39,0,4,838,0,1,107,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3179_V06,0,1,0,4,7,0,17,2,22,0,...,0,0,31,0,2,783,8,3,134,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
4019_V04,0,0,0,0,5,0,31,0,0,0,...,2,0,50,0,2,827,0,3,120,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3120_BL,0,0,0,9,7,2,21,0,43,0,...,0,1,32,1,3,384,4,4,45,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3865_BL,0,0,1,0,7,9,58,0,7,0,...,1,2,75,0,2,1658,0,5,239,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
3573_V06,0,0,0,0,14,1,48,0,1,0,...,0,0,65,0,0,1533,0,0,96,"[[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."

In [65]:
X_train_transpot = X_train.drop(['img_array'],axis=1)
X_val_transpot = X_val.drop(['img_array'],axis=1)
X_test_transpot = X_test.drop(['img_array'],axis=1)

In [66]:
X_train_transpot

,ENSG00000242268.2,ENSG00000259041.1,ENSG00000207641.1,ENSG00000270112.3,ENSG00000280143.1,ENSG00000269416.5,ENSG00000263642.1,ENSG00000225275.4,ENSG00000158486.13,ENSG00000283967.1,...,ENSG00000009694.13,ENSG00000238244.3,ENSG00000216352.1,ENSG00000123685.8,ENSG00000267117.1,ENSG00000265520.1,ENSG00000105063.18,ENSG00000181518.4,ENSG00000231119.2,ENSG00000178921.13
PATNO Visit,,,,,,,,,,,,,,,,,,,,,
3390_BL,2,0,0,16,11,3,23,1,19,0,...,900,0,0,79,2,2,619,5,4,81
4020_V06,0,2,0,2,8,3,22,0,19,0,...,616,2,0,36,0,1,582,7,2,63
4020_BL,0,0,0,0,8,0,46,2,1,0,...,980,3,0,42,0,0,1482,0,0,114
3770_V04,0,0,1,0,0,1,8,0,5,0,...,289,1,0,32,0,2,401,0,2,53
3165_BL,0,0,0,0,13,0,27,0,2,0,...,606,2,0,41,0,2,958,0,2,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3173_BL,0,0,0,0,8,0,27,0,3,0,...,1404,0,0,118,0,9,2458,0,2,269
3119_BL,0,0,0,2,8,0,64,2,3,0,...,451,0,0,105,0,0,1420,0,1,185
3752_V06,0,0,0,0,18,0,29,0,5,0,...,1286,1,0,264,0,9,1506,0,4,268
3132_V04,2,0,0,5,14,1,30,1,8,0,...,561,0,0,34,0,1,736,1,3,91
3182_BL,4,4,0,28,20,5,52,3,97,0,...,1137,3,1,60,2,1,644,7,4,80

In [67]:
img_cols = list(set(img.columns) - set(["PATNO Visit","label"]))
print(len(img.columns))
print(len(img_cols))
X_train_img = X_train[img_cols]
X_val_img = X_val[img_cols]
X_test_img = X_test[img_cols]

3
1

In [68]:
X_train_img.shape

(375, 1)

In [69]:
X_train_transpot.shape

(375, 57703)

In [70]:
X_train_img.shape

(375, 1)

In [71]:
X_train_transpot

,ENSG00000242268.2,ENSG00000259041.1,ENSG00000207641.1,ENSG00000270112.3,ENSG00000280143.1,ENSG00000269416.5,ENSG00000263642.1,ENSG00000225275.4,ENSG00000158486.13,ENSG00000283967.1,...,ENSG00000009694.13,ENSG00000238244.3,ENSG00000216352.1,ENSG00000123685.8,ENSG00000267117.1,ENSG00000265520.1,ENSG00000105063.18,ENSG00000181518.4,ENSG00000231119.2,ENSG00000178921.13
PATNO Visit,,,,,,,,,,,,,,,,,,,,,
3390_BL,2,0,0,16,11,3,23,1,19,0,...,900,0,0,79,2,2,619,5,4,81
4020_V06,0,2,0,2,8,3,22,0,19,0,...,616,2,0,36,0,1,582,7,2,63
4020_BL,0,0,0,0,8,0,46,2,1,0,...,980,3,0,42,0,0,1482,0,0,114
3770_V04,0,0,1,0,0,1,8,0,5,0,...,289,1,0,32,0,2,401,0,2,53
3165_BL,0,0,0,0,13,0,27,0,2,0,...,606,2,0,41,0,2,958,0,2,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3173_BL,0,0,0,0,8,0,27,0,3,0,...,1404,0,0,118,0,9,2458,0,2,269
3119_BL,0,0,0,2,8,0,64,2,3,0,...,451,0,0,105,0,0,1420,0,1,185
3752_V06,0,0,0,0,18,0,29,0,5,0,...,1286,1,0,264,0,9,1506,0,4,268
3132_V04,2,0,0,5,14,1,30,1,8,0,...,561,0,0,34,0,1,736,1,3,91
3182_BL,4,4,0,28,20,5,52,3,97,0,...,1137,3,1,60,2,1,644,7,4,80

In [72]:
X_train_img

                                                     img_array
PATNO Visit
3390_BL      [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
4020_V06     [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
4020_BL      [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
3770_V04     [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
3165_BL      [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
...                                                        ...
3173_BL      [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
3119_BL      [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
3752_V06     [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
3132_V04     [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
3182_BL      [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...

[375 rows x 1 columns]

In [73]:
X_train_transpot.to_csv("../../processed_data/PPMI/overlap/X_train_transpot.csv")
X_val_transpot.to_csv("../../processed_data/PPMI/overlap/X_val_transpot.csv")
X_test_transpot.to_csv("../../processed_data/PPMI/overlap/X_test_transpot.csv")

y_train.to_csv("../../processed_data/PPMI/overlap/y_train.csv")
y_val.to_csv("../../processed_data/PPMI/overlap/y_val.csv")
y_test.to_csv("../../processed_data/PPMI/overlap/y_test.csv")

# X_train_img.to_csv("../../processed_data/PPMI/overlap/X_train_img.csv")
# X_test_img.to_csv("../../processed_data/PPMI/overlap/X_test_img.csv")

In [74]:
pd.DataFrame(X_train_img).to_pickle("../../processed_data/PPMI/overlap/X_train_img.pkl")
pd.DataFrame(X_val_img).to_pickle("../../processed_data/PPMI/overlap/X_val_img.pkl")
pd.DataFrame(X_test_img).to_pickle("../../processed_data/PPMI/overlap/X_test_img.pkl")

In [75]:
X_train_img['img_array'][11].shape

(3, 72, 72)